# Generated by Django 5.0.1 on 2025-06-20 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0003_artikel_gambar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Artikel'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Kategori'},
        ),
        migrations.AddField(
            model_name='artikel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artikels', to='artikel.kategori'),
        ),
    ]
